import type { AiPlayerActionCatalogEntry } from '../../../../shared/contracts/aiPlayer'

export const AI_PLAYER_ACTION_CATALOG: readonly AiPlayerActionCatalogEntry[] = [
  { action: 'ai_player_pause', category: 'governance', label: 'Pause AI Player', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false, notes: 'Governance-only action; formal runtime mutation not wired in v1.' },
  { action: 'ai_player_resume', category: 'governance', label: 'Resume AI Player', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false, notes: 'Governance-only action; formal runtime mutation not wired in v1.' },
  { action: 'ai_player_set_control_mode', category: 'governance', label: 'Set Control Mode', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_set_action_whitelist', category: 'governance', label: 'Set Action Whitelist', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_set_budget', category: 'governance', label: 'Set Budget', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_set_schedule_window', category: 'governance', label: 'Set Schedule Window', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_assign_governor', category: 'governance', label: 'Assign Governor', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_transfer_governor', category: 'governance', label: 'Transfer Governor', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_takeover', category: 'governance', label: 'Human Takeover', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'ai_player_release_takeover', category: 'governance', label: 'Release Takeover', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'city_upgrade', category: 'city', label: 'Upgrade City', riskLevel: 'low', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'upgradeCity', notes: 'First executable player action in v1.' },
  { action: 'building_upgrade', category: 'city', label: 'Upgrade Building', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'promoteCityBuilding', notes: 'Auto-resolves a safe owned city building target when omitted.' },
  { action: 'research_start', category: 'city', label: 'Start Research', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'upgradeCityTech', notes: 'Auto-resolves owned city hall and defaults to a safe city-tech track when omitted.' },
  { action: 'troop_train', category: 'city', label: 'Train Troops', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'deployReserveHero', notes: 'Auto-resolves the first reserve hero and faction home tile when omitted.' },
  { action: 'troop_heal', category: 'city', label: 'Heal Troops', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'queue_fill_idle_slot', category: 'city', label: 'Fill Idle Queue', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: true, mappedWorldAction: 'enqueueAffair', notes: 'Auto-resolves the first idle city affair slot when omitted.' },
  { action: 'recruit_pool_select', category: 'city', label: 'Select Recruit Pool', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: true, mappedWorldAction: 'setRecruitSelectedPool', notes: 'Auto-resolves the first recruit pool that differs from the current authority state when omitted.' },
  { action: 'speedup_use', category: 'city', label: 'Use Speedup', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'resource_item_use', category: 'city', label: 'Use Resource Item', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'boost_item_use', category: 'city', label: 'Use Boost Item', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'recruit_commander', category: 'city', label: 'Recruit Commander', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'recruitProspectHero', notes: 'Auto-resolves the active recruit pool and defaults to a single draw.' },
  { action: 'world_scout', category: 'world', label: 'Scout World Target', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: true, mappedWorldAction: 'queuePlanExecution', notes: 'Auto-resolves a faction unit and adjacent intel target, then queues a single recon order with reject_if_active guard.' },
  { action: 'march_move', category: 'world', label: 'Move March', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'moveUnit', notes: 'Auto-resolves a faction unit and adjacent safe target tile when omitted.' },
  { action: 'march_recall', category: 'world', label: 'Recall March', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'resource_gather', category: 'world', label: 'Gather Resources', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'garrison_set', category: 'world', label: 'Set Garrison', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'queueTacticalOverride', notes: 'Auto-resolves a faction unit and defaults the garrison target to the unit current tile.' },
  { action: 'troop_facility_upgrade', category: 'world', label: 'Upgrade Troop Facility', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'promoteTroopFacilityBuilding', notes: 'Auto-resolves a faction unit and defaults facility/building ids to the first troop-panel authority path when omitted.' },
  { action: 'general_focus_set', category: 'world', label: 'Set General Focus', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: true, mappedWorldAction: 'setGeneralActiveHero', notes: 'Auto-resolves a roster hero and defaults to deployed, active, or recent hero state when omitted.' },
  { action: 'tile_occupy', category: 'world', label: 'Occupy Tile', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'wild_attack', category: 'world', label: 'Attack Wild Target', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'teleport_use', category: 'world', label: 'Use Teleport', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'formation_assign', category: 'world', label: 'Assign Formation', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'setGeneralTactic', notes: 'Auto-resolves a faction field hero and defaults to the first tactic that differs from the current authority state.' },
  { action: 'threat_escape', category: 'world', label: 'Escape Threat', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'queueAiAgendaAction', notes: 'Auto-resolves agenda_recover or agenda_redeploy from the primary unit threat state when omitted.' },
  { action: 'alliance_help', category: 'alliance', label: 'Alliance Help', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: true, mappedWorldAction: 'allianceHelp', notes: 'Auto-resolves the weakest alliance directive region when omitted.' },
  { action: 'resource_transfer_to_governor', category: 'economy', label: 'Transfer Resources To Governor', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: true, mappedWorldAction: 'transferFactionResourcesToGovernor', notes: 'Transfers from the AI resource subaccount into the same-governor pending inbox; cross-faction trade is deferred.' },
  { action: 'alliance_donate', category: 'alliance', label: 'Alliance Donate', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'rally_join', category: 'alliance', label: 'Join Rally', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'rally_launch', category: 'alliance', label: 'Launch Rally', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'alliance_relocate', category: 'alliance', label: 'Relocate Near Alliance', riskLevel: 'high', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'alliance_task_execute', category: 'alliance', label: 'Alliance Task Execute', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'alliance_mail_ack', category: 'alliance', label: 'Acknowledge Alliance Mail', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'daily_task_execute', category: 'activity', label: 'Execute Daily Task', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'reward_claim', category: 'activity', label: 'Claim Reward', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: true, mappedWorldAction: 'claimReward', notes: 'Auto-resolves the newest pending faction reward when omitted.' },
  { action: 'event_task_execute', category: 'activity', label: 'Execute Event Task', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'event_priority_sort', category: 'activity', label: 'Sort Event Priority', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'stamina_spend', category: 'activity', label: 'Spend Stamina', riskLevel: 'medium', requiresApprovalByDefault: true, executableInV1: false },
  { action: 'activity_window_enter', category: 'activity', label: 'Enter Activity Window', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'battle_report_read', category: 'intel', label: 'Read Battle Report', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'failure_reason_summarize', category: 'intel', label: 'Summarize Failure Reason', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'enemy_pressure_estimate', category: 'intel', label: 'Estimate Enemy Pressure', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'threat_alert_emit', category: 'intel', label: 'Emit Threat Alert', riskLevel: 'medium', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'next_step_propose', category: 'intel', label: 'Propose Next Step', riskLevel: 'low', requiresApprovalByDefault: false, executableInV1: false },
  { action: 'human_escalation_request', category: 'intel', label: 'Request Human Escalation', riskLevel: 'medium', requiresApprovalByDefault: false, executableInV1: false },
] as const

export function listStaticAiPlayerActionCatalog(): AiPlayerActionCatalogEntry[] {
  return AI_PLAYER_ACTION_CATALOG.map((entry) => ({ ...entry }))
}
